# Тема “Вычисления с помощью Numpy”

#### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [8]:
import numpy as np

In [24]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [27]:
a_mean = a.mean(axis=0)
a_mean

array([2. , 8.4])

#### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [29]:
a_centered = np.subtract(a, a_mean)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [32]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])
a_centered_sp

8.0

In [49]:
a_cov = a_centered_sp / (a.shape[0] - 1)
a_cov

2.0

# Тема “Работа с данными в Pandas”

#### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [52]:
import pandas as pd

In [62]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Turgenev', 'Chekhov', 'Ostrovskiy']
})
authors

author_id author_name
0          1    Turgenev
1          2     Chekhov
2          3  Ostrovskiy

In [63]:
books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Father ans Sons', 'Rudin', 'A House of Gentlefolk', 'Fat and thin', 'The lady with the dog', 'The storm', 'Talanstes and admirers'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
books

author_id              book_title  price
0          1         Father ans Sons    450
1          1                   Rudin    300
2          1   A House of Gentlefolk    350
3          2            Fat and thin    500
4          2   The lady with the dog    450
5          3               The storm    370
6          3  Talanstes and admirers    290

#### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [69]:
authors_price = pd.merge(authors, books, on='author_id')
authors_price

author_id author_name              book_title  price
0          1    Turgenev         Father ans Sons    450
1          1    Turgenev                   Rudin    300
2          1    Turgenev   A House of Gentlefolk    350
3          2     Chekhov            Fat and thin    500
4          2     Chekhov   The lady with the dog    450
5          3  Ostrovskiy               The storm    370
6          3  Ostrovskiy  Talanstes and admirers    290

#### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [89]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name             book_title  price
3          2     Chekhov           Fat and thin    500
0          1    Turgenev        Father ans Sons    450
4          2     Chekhov  The lady with the dog    450
5          3  Ostrovskiy              The storm    370
2          1    Turgenev  A House of Gentlefolk    350

#### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

In [104]:
authours_stat = pd.DataFrame({
    'author_name': authors_price['author_name'].unique(),
    'min_price': authors_price.groupby('author_name', sort=False)['price'].min(),
    'max_price': authors_price.groupby('author_name', sort=False)['price'].max(),
    'mean_price' : authors_price.groupby('author_name', sort=False)['price'].mean()
})
authours_stat.style.hide_index()